### ISSUE TITLE
About figure of features

### ISSUE THREAD

**Issue by zorrocai** [jxgu1016/MNIST_center_loss_pytorch#8]
I wonder that how to change the code to plot the figure of features with only softmax loss.
And what do you think about the different  shape between the Fig.3 in original paper and the figure produced though your codes.
![image](https://user-images.githubusercontent.com/24424749/41356747-1a00e1d0-6f57-11e8-9a0f-502d6b42a7e0.png)
![image](https://user-images.githubusercontent.com/24424749/41356801-344ffc88-6f57-11e8-8348-deca64438d65.png)

**Comment by jxgu1016** [comment]
1. set ```loss_weight``` to 0
2. I guess that difference may be caused by the initialization of the **centers**. They may initialize them around a circle.

**Comment by zorrocai** [comment]
I tried the circular initialization, and it doesn't match your guess.

**Comment by zchky** [comment]
@zorrocai 

set the bias to False, you can get the circle

**Comment by jxgu1016** [comment]
Interesting, did you find the solution yourself on this code or refer to other issues on other repo? @zchky

**Comment by zchky** [comment]
more specifically

Drop the bias of last fully connected layer.

**Comment by jxgu1016** [comment]
See Fig. 3 in the paper of [NormFace](http://www.cs.jhu.edu/~alanlab/Pubs17/wang2017normface.pdf).
